//
//  ImageListModels.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImageList
{
    // MARK: Use cases
    enum FetchImageURL
    {
        struct Response
        {
            let startIndex: Int
            let endIndex: Int
            let urls: [String]
        }
        struct ViewModel
        {
            let startIndex: Int
            let endIndex: Int
            let urls: [String]
        }
    }
    
    enum GetImage {
        struct Response
        {
            let rowUpdate: Int
            let img: UIImage?
        }
        struct ViewModel
        {
            let rowUpdate: Int
            let img: UIImage?
        }
    }
}
