//
//  ImageListRouter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImageListRoutingLogic
{
    func routeToImageDetail()
}

protocol ImageListDataPassing
{
    var dataStore: ImageListDataStore? { get }
}

class ImageListRouter: NSObject, ImageListRoutingLogic, ImageListDataPassing
{
    weak var viewController: ImageListViewController?
    var dataStore: ImageListDataStore?
    
    // MARK: Routing
    
    func routeToImageDetail()
    {
        let storyboard = UIStoryboard(name: "ImageDetailStoryboard", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ImageDetailViewController") as! ImageDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToImageDetail(source: dataStore!, destination: &destinationDS)
        navigateToImageDetail(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToImageDetail(source: ImageListViewController, destination: ImageDetailViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToImageDetail(source: ImageListDataStore, destination: inout ImageDetailDataStore) {
        destination.idImageDetail = source.idImageDetail
    }
}
