//
//  ImageListPresenter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListPresentationLogic
{
    func presentGetImagesPicsum(response: ImageList.FetchImageURL.Response)
}

class ImageListPresenter: ImageListPresentationLogic
{
    weak var viewController: ImageListDisplayLogic?
    
    // MARK: ImageListPresentationLogic
    
    func presentGetImagesPicsum(response: ImageList.FetchImageURL.Response) {
        let viewModel = ImageList.FetchImageURL.ViewModel(startIndex: response.startIndex, endIndex: response.endIndex, urls: response.urls)
        viewController?.displayGetImagesPicsum(viewModel: viewModel)
    }
}
