//
//  ImageListViewController.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListDisplayLogic: AnyObject
{
    func displayGetImagesPicsum(viewModel: ImageList.FetchImageURL.ViewModel)
    func displayOpenDetailImage()
}

class ImageListViewController: UIViewController, ImageListDisplayLogic
{
    @IBOutlet weak var imagesCollectionView: UICollectionView!
    
    var interactor: ImageListBusinessLogic?
    var router: (NSObjectProtocol & ImageListRoutingLogic & ImageListDataPassing)?
    
    private var imageURLs: [String] = []
    private var loadedImageList: [String: Data?] = [:]
    
    // MARK: Object lifecycle
    override func awakeFromNib() {
        super.awakeFromNib()
        setup()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        getImagesPicsum()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = ImageListInteractor()
        let presenter = ImageListPresenter()
        let router = ImageListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //MARK: View
    private func setupView() {
        //set Navigation Bar
        self.navigationItem.title = "PICSUM DEMO"
        self.navigationController?.navigationBar.prefersLargeTitles = true
        self.navigationItem.largeTitleDisplayMode = .always
        self.navigationController?.navigationBar.barTintColor = UIColor.lightGray
        self.navigationController?.navigationBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.black]
        
        let nib = UINib(nibName: "ImageViewCell", bundle: nil)
        imagesCollectionView.register(nib, forCellWithReuseIdentifier: "ImageViewCell")
        
        imagesCollectionView.delegate = self
        imagesCollectionView.dataSource = self
    }
    
    // MARK: Function
    func getImagesPicsum() {
        interactor?.getImagesPicsum()
    }
    
    private func clearMemoryOfOldCacheImage() {
        self.loadedImageList = [:]
    }
    
    // MARK: ImageListDisplayLogic
    func displayGetImagesPicsum(viewModel: ImageList.FetchImageURL.ViewModel) {
        // Load a batch of images starting from the given index
        self.imageURLs += viewModel.urls
        imagesCollectionView.reloadData()
    }
    
    func displayOpenDetailImage() {
        self.router?.routeToImageDetail()
    }
}


extension ImageListViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return imageURLs.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ImageViewCell", for: indexPath) as! ImageViewCell
        cell.delegate = self
        self.interactor?.setCurrentIndex(index: indexPath.row)
        
        if let imageDataCache = loadedImageList[imageURLs[indexPath.row]] ,
            let dataImg = imageDataCache,
            let imageCache = UIImage(data: dataImg) {
            cell.setImageCache(image: imageCache)
        } else {
            cell.configureCell(imageUrl: imageURLs[indexPath.row])
        }
        
        //fetch more when find last index
        let isLastRow = indexPath.row == imageURLs.count - 1
        if isLastRow {
            self.clearMemoryOfOldCacheImage()
            self.interactor?.fetchMoreImagesPicsum()
        }
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let id = indexPath.row
        if let imageDataCache = loadedImageList[imageURLs[indexPath.row]] ,
           let data = imageDataCache {
            self.interactor?.openDetailImage(imageDetailInfo: ImageDetailInfo(idImageDetail: id, dataImageDetail: data))
        }
        
    }

    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        cell.fadeAnimation()
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let width = self.view.bounds.width
        let height = CGFloat(300)
        return CGSize(width: width, height: height)
    }
}

extension ImageListViewController: ImageViewCellDelegate {
    func keepCacheImage(urlCache: String,imageCache: UIImage?) {
        if let imgDataCache = imageCache?.pngData() {
            loadedImageList[urlCache] = imgDataCache
        }
    }
}
