//
//  ImageListPresenter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListPresentationLogic
{
    func presentSomething(response: ImageList.Something.Response)
}

class ImageListPresenter: ImageListPresentationLogic
{
    weak var viewController: ImageListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ImageList.Something.Response)
    {
        let viewModel = ImageList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
