//
//  ImageListWorker.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageListWorkerInterface {
    func generateListURL(startIndex: Int, endIndex: Int, success:([String]) -> Void)
}

class ImageListWorker: ImageListWorkerInterface
{
    func generateListURL(startIndex: Int, endIndex: Int, success:([String]) -> Void) {
        let listImageURL = (startIndex...endIndex).map {
            ImageLoaderManager.shared.getURLSpecificImageLoad(id: $0)
        }
        success(listImageURL)
    }
}
