//
//  FullImageWorker.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 18/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullImageWorkerInterface {
    func loadImageDetailInfo(id: Int ,success: @escaping (DetailDisplayModel) -> Void ,fail: @escaping (Error) -> Void)
}

class FullImageWorker: FullImageWorkerInterface
{
    var service: ImageDetailServiceInterface!
    
    init(service: ImageDetailServiceInterface) {
        self.service = service
    }
    
    func loadImageDetailInfo(id: Int ,success: @escaping (DetailDisplayModel) -> Void ,fail: @escaping (Error) -> Void) {
        let url = ImageLoaderManager.shared.getURLImageDetail(id: id)
        service.loadImageDetail(url: url) { result in
            switch result {
            case .success(let response):
                success(response)
            case .failure(let error):
                fail(error)
            }
        }
    }
    
}
