//
//  FullImagePresenter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 18/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullImagePresentationLogic
{
    func presentGetImageDetail(response: FullImage.GetDetailDisplay.Response)
}

class FullImagePresenter: FullImagePresentationLogic
{
    weak var viewController: FullImageDisplayLogic?
    
    // MARK: FullImagePresentationLogic
    
    func presentGetImageDetail(response: FullImage.GetDetailDisplay.Response)
    {
        let urlDetailImage = response.displayModel.url
        
        let viewModel = FullImage.GetDetailDisplay.ViewModel(url: urlDetailImage)
        viewController?.displayGetImageDetail(viewModel: viewModel)
    }
    
}
