//
//  FullImageInteractor.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 18/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullImageBusinessLogic
{
    func getImageDetail()
}

protocol FullImageDataStore
{
    var imageDetailInfo: ImageDetailInfo? { get set }
}

class FullImageInteractor: FullImageBusinessLogic, FullImageDataStore
{
    var presenter: FullImagePresentationLogic?
    var worker: FullImageWorker = FullImageWorker(service: ImageCommonService())
    
    var imageDetailInfo: ImageDetailInfo? = nil
    
    // MARK: ImageDetailBusinessLogic
    
    func getImageDetail() {
        if let request = imageDetailInfo {
            worker.loadImageDetailInfo(id: request.idImageDetail) {[weak self] detailDisplayModel in
                guard let self = self else { return }
                let response = FullImage.GetDetailDisplay.Response(imageData: request.dataImageDetail, displayModel: detailDisplayModel)
                self.presenter?.presentGetImageDetail(response: response)
            } fail: { error in
                print(error.localizedDescription)
            }
        }
    }
}
