//
//  ImageDetailWorker.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailWorkerInterface {
    func loadImageDetailInfo(id: Int) async throws -> DetailDisplayModel
    func loadImageBlur(url: String) async throws -> UIImage
    func loadImageGrayScale(url: String) async throws -> UIImage
}

class ImageDetailWorker: ImageDetailWorkerInterface
{
    var service: ImageDetailService!
    
    init(service: ImageDetailService) {
        self.service = service
    }
    
    func loadImageDetailInfo(id: Int) async throws -> DetailDisplayModel {
        let url = ImageLoaderManager.shared.getURLImageDetail(id: id)
        let response = try await service.loadImageDetail(url: url)
        return response
    }
    
    func loadImageBlur(url: String) async throws -> UIImage {
        let imageBlurResponse = try await ImageLoaderManager.shared.loadImage(from: url)
        return imageBlurResponse
    }
    
    func loadImageGrayScale(url: String) async throws -> UIImage {
        let imageGrayScaleResponse = try await ImageLoaderManager.shared.loadImage(from: url)
        return imageGrayScaleResponse
    }
}
