//
//  ImageDetailViewController.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailDisplayLogic: AnyObject
{
    func displayGetImageDetail(viewModel: ImageDetail.GetDetailDisplay.ViewModel)
}

class ImageDetailViewController: UIViewController, ImageDetailDisplayLogic
{
    
    @IBOutlet weak var detailImageView: UIImageView!
    @IBOutlet weak var blurSlider: UISlider!
    @IBOutlet weak var lblAuthor: UILabel!
    @IBOutlet weak var descTextView: UITextView!
    @IBOutlet weak var typeSegment: UISegmentedControl!
    
    var interactor: ImageDetailBusinessLogic?
    var router: (NSObjectProtocol & ImageDetailRoutingLogic & ImageDetailDataPassing)?
    
    private var segmentTypeSelected: SegmentType = .normal
    private var normalImage: Data? = nil
    private var blurImage: Data? = nil
    private var grayScaleImage: Data? = nil
    
    // MARK: Object lifecycle
    override func awakeFromNib() {
        super.awakeFromNib()
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = ImageDetailInteractor()
        let presenter = ImageDetailPresenter()
        let router = ImageDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setUpView()
        setUpSegmentView()
        getImageDetail()
    }
    
    // MARK: View
    private func setUpView() {
        
    }
    
    private func setUpSegmentView() {
        switch segmentTypeSelected {
        case .normal:
            blurSlider.isHidden = true
            break
        case .blur:
            blurSlider.isHidden = false
            break
        case .grayScale:
            blurSlider.isHidden = true
            break
        }
        
        typeSegment.selectedSegmentIndex = segmentTypeSelected.rawValue
    }
    
    // MARK: Function
    func getImageDetail() {
        interactor?.getImageDetail()
    }
    
    // MARK: Event UI Action
    
    @IBAction func typeSegment_click(_ sender: UISegmentedControl) {
        segmentTypeSelected = sender.selectedSegmentIndex.toSegmentType()
        setUpSegmentView()
    }
    
    // MARK: ImageDetailDisplayLogic
    func displayGetImageDetail(viewModel: ImageDetail.GetDetailDisplay.ViewModel) {
        DispatchQueue.main.async {
            self.normalImage = viewModel.imageData
            self.detailImageView.image = UIImage(data: self.normalImage ?? Data())
            self.lblAuthor.text = viewModel.author
            self.descTextView.text = viewModel.desc
        }
    }
}
