//
//  ImageDetailRouter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImageDetailRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ImageDetailDataPassing
{
    var dataStore: ImageDetailDataStore? { get }
}

class ImageDetailRouter: NSObject, ImageDetailRoutingLogic, ImageDetailDataPassing
{
    weak var viewController: ImageDetailViewController?
    var dataStore: ImageDetailDataStore?
    
    // MARK: Routing
    
    // MARK: Navigation
    
    // MARK: Passing data
    
}
