//
//  ImageDetailInteractor.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailBusinessLogic
{
    func doSomething(request: ImageDetail.Something.Request)
}

protocol ImageDetailDataStore
{
    var imageDetailInfo: ImageDetailInfo? { get set }
}

class ImageDetailInteractor: ImageDetailBusinessLogic, ImageDetailDataStore
{
    
    
    var presenter: ImageDetailPresentationLogic?
    var worker: ImageDetailWorker = ImageDetailWorker(service: ImageDetailService())
    
    var imageDetailInfo: ImageDetailInfo? = nil
    
    // MARK: Do something
    
    func doSomething(request: ImageDetail.Something.Request)
    {
        worker.loadImageDetail()
        let response = ImageDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
