//
//  ImageDetailPresenter.swift
//  PicsumListDemo
//
//  Created by Papon Supamongkonchai on 24/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailPresentationLogic
{
    func presentSomething(response: ImageDetail.Something.Response)
}

class ImageDetailPresenter: ImageDetailPresentationLogic
{
    weak var viewController: ImageDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ImageDetail.Something.Response)
    {
        let viewModel = ImageDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
